{
 "title": "Disk Usage Metrics",
 "tags": [ "disk usage metrics" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Disk Space Used (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "disk_used_percent", "legendFormat": "{{device}} on {{path}}" }
   ]
  },
  {
   "title": "Disk Inodes Used (%)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "disk_inodes_used_percent", "legendFormat": "{{device}} on {{path}}" }
   ]
  },
  {
   "title": "Disk Space Used (Bytes)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "disk_used", "legendFormat": "{{device}} on {{path}}" }
   ]
  },
  {
   "title": "Disk Space Total (Bytes)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "disk_total", "legendFormat": "{{device}} on {{path}}" }
   ]
  }
 ]
}