{
 "title": "Zookeeper",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "zk_cluster", "label": "zk_cluster", "query": { "query": "label_values(zk_up,zk_cluster)" } }
  ]
 },
 "panels": [
  { "title": "分组", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "zk_up{zk_cluster=\"$zk_cluster\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Is Leader",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "zk_server_leader{zk_cluster=~\"$zk_cluster\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Ephemerals Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "zk_ephemerals_count{zk_cluster=~\"$zk_cluster\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Znode Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "zk_znode_count{zk_cluster=~\"$zk_cluster\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Watch Count",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "zk_watch_count{zk_cluster=~\"$zk_cluster\"}",
     "legendFormat": "{{zk_host}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "zk_version{zk_cluster=~\"$zk_cluster\"}"
    }
   ]
  },
  {
   "title": "Pakages Sent",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(zk_packets_sent{zk_cluster=~\"$zk_cluster\"}[5m])",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Pakages Recieved",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "rate(zk_packets_received{zk_cluster=~\"$zk_cluster\"}[5m])",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Alive Connections",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "zk_num_alive_connections{zk_cluster=~\"$zk_cluster\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "zk_open_file_descriptor_count{zk_cluster=~\"$zk_cluster\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "zk_avg_latency{zk_cluster=~\"$zk_cluster\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Min Latency(seconds)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "zk_min_latency{zk_cluster=~\"$zk_cluster\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Max Latency(seconds)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "expr": "zk_max_latency{zk_cluster=~\"$zk_cluster\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "zk_outstanding_requests{zk_cluster=~\"$zk_cluster\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  },
  {
   "title": "Approx Data Size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "zk_approximate_data_size{zk_cluster=~\"$zk_cluster\"}",
     "legendFormat": "{{ zk_host }}"
    }
   ]
  }
 ]
}