{
 "title": "SQLServer",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(sqlserver_up,sql_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server resource overview",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Total Server Memory (KB)\",serverName=\"$instance\"}",
     "legendFormat": "Total RAM"
    },
    {
     "expr": "sqlserver_performance_value{counter=\"Total Server Memory (KB)\",serverName=\"$instance\"}-sqlserver_performance_value{counter=\"Used memory (KB)\",serverName=\"$instance\"}",
     "legendFormat": "RAM availbable"
    },
    {
     "expr": "sqlserver_performance_value{counter=\"Free Space in tempdb (KB)\",serverName=\"$instance\"}",
     "legendFormat": "Pagefile  available size"
    },
    {
     "expr": "sqlserver_performance_value{counter=\"Page life expectancy\",serverName=\"$instance\"}",
     "legendFormat": "Total page faults"
    },
    {
     "expr": "sqlserver_performance_value{counter=\"Batch Requests/sec\",serverName=\"$instance\"}",
     "legendFormat": "Batch reqs /sec"
    },
    {
     "expr": "sqlserver_performance_value{counter=\"Page life expectancy\",serverName=\"$instance\"}",
     "legendFormat": "Page life expectancy(sec)"
    },
    {
     "expr": "sqlserver_performance_value{counter=\"Number of Deadlocks/sec\",serverName=\"$instance\"}",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sqlserver_performance_value{counter=\"Errors/sec\",serverName=\"$instance\"}",
     "legendFormat": "User errors /sec"
    },
    {
     "expr": "mssql_kill_connection_errors{job=~\"$Job\"}-0",
     "legendFormat": "Kill conn errors /sec"
    },
    {
     "expr": "sqlserver_cpu_system_idle_cpu{serverName=\"$instance\"}",
     "legendFormat": "sqlserver_cpu_system_idle"
    },
    {
     "expr": "sqlserver_up{serverName=\"$instance\"}",
     "legendFormat": "sqlserver_up"
    }
   ]
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "当前数据库连接",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Logical Connections\",serverName=\"$instance\"}",
     "legendFormat": "{{sql_instance}} "
    }
   ]
  },
  {
   "title": "DB Log growth since last restart",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 4 },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Log Growths\",serverName=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of Deadlocks/sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sqlserver_performance_value{counter=\"Number of Deadlocks/sec\",serverName=\"$instance\"}",
     "legendFormat": "Number of Deadlocks/sec"
    }
   ]
  },
  {
   "title": "硬盘空闲空间",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sqlserver_volume_space_available_space_bytes{serverName=\"$instance\"}",
     "legendFormat": "硬盘空闲空间"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 11 },
   "targets": [
    {
     "expr": "sqlserver_cpu_sqlserver_process_cpu{serverName=\"$instance\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Total wait time of I/O stall",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sqlserver_database_io_read_latency_ms{serverName=\"$instance\",database_name=\"h3cloud\"}",
     "legendFormat": "io_read_latency_ms"
    }
   ]
  },
  {
   "title": "Database I/O wait of stall detailed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }
  },
  {
   "title": "Database wait by I/O stall ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sqlserver_database_io_rg_write_stall_ms{serverName=\"$instance\"}+sqlserver_database_io_rg_read_stall_ms{serverName=\"$instance\"}",
     "legendFormat": "{{database_name}}"
    }
   ]
  }
 ]
}