{
 "title": "PING大盘2.0",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "连通性",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(ping_result_code) by (target,subnet)",
     "legendFormat": "源地址: {{subnet}}  目标地址:{{target}}"
    }
   ]
  },
  {
   "title": "延迟",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "max(ping_maximum_response_ms) by (target,subnet)",
     "legendFormat": "源地址: {{subnet}}  目标地址:{{target}}"
    }
   ]
  },
  {
   "title": "TTL",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "max(ping_ttl) by (target,subnet)",
     "legendFormat": "探测源: {{subnet}}目标地址: {{target }}  TTL"
    }
   ]
  },
  {
   "title": "丢包率",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max(ping_percent_packet_loss) by (subnet,target)",
     "legendFormat": "目标地址: {{target}}"
    }
   ]
  },
  { "title": "Panel 5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } }
 ]
}