{
 "title": "HAProxy By Categraf",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "ident", "label": "ident", "query": { "query": "label_values(haproxy_up,ident)" } },
   {
    "name": "frontend",
    "label": "frontend",
    "query": {
     "query": "label_values(haproxy_frontend_bytes_in_total{ident=\"$ident\"}, frontend)"
    }
   },
   {
    "name": "backend",
    "label": "backend",
    "query": {
     "query": "label_values(haproxy_backend_bytes_in_total{ident=\"$ident\"}, backend)"
    }
   },
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(haproxy_server_bytes_in_total{ident=\"$ident\", backend=~\"$backend\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{ident=\"$ident\",backend=~\"$backend\", server=~\"$server\"}, code)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Stats API UP?",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "haproxy_up" }
   ]
  },
  {
   "title": "Backends UP?",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "haproxy_backend_up{ident=\"$ident\"}"
    }
   ]
  },
  {
   "title": "Servers UP?",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "haproxy_server_up{ident=\"$ident\"}"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{frontend=~\"$frontend\",ident=\"$ident\"}) by (frontend)",
     "legendFormat": "Front-{{frontend}}"
    },
    {
     "expr": "sum(haproxy_backend_current_sessions{backend=~\"$backend\",ident=\"$ident\"}) by (backend)",
     "legendFormat": "Back-{{backend}}"
    }
   ]
  },
  {
   "title": "Frontend responses by code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{frontend=~\"$frontend\",code=~\"$code\",ident=\"$ident\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Backend responses by code",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{backend=~\"$backend\",code=~\"$code\",ident=\"$ident\"}[5m])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "Incoming / Outgoing bits (Frontend)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_bytes_in_total{frontend=~\"$frontend\",ident=\"$ident\"}[5m])*8) by (frontend)",
     "legendFormat": "IN {{frontend}}"
    },
    {
     "expr": "-sum(rate(haproxy_frontend_bytes_out_total{frontend=~\"$frontend\",ident=\"$ident\"}[5m])*8) by (frontend)",
     "legendFormat": "OUT {{frontend}}"
    }
   ]
  },
  {
   "title": "Incoming / Outgoing bits(Backend)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{backend=~\"$backend\",ident=\"$ident\"}[5m])*8) by (backend)",
     "legendFormat": "IN {{backend}}"
    },
    {
     "expr": "-sum(rate(haproxy_backend_bytes_out_total{backend=~\"$backend\",ident=\"$ident\"}[5m])*8) by (backend)",
     "legendFormat": "OUT {{backend}}"
    }
   ]
  },
  {
   "title": "Frontend Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_requests_total{frontend=~\"$frontend\",ident=\"$ident\"}[5m])) by (frontend)",
     "legendFormat": "Front requests - {{frontend}}"
    },
    {
     "expr": "sum(rate(haproxy_frontend_request_errors_total{frontend=~\"$frontend\",ident=\"$ident\"}[5m])) by (frontend)",
     "legendFormat": "Front requests errors - {{frontend}}"
    },
    {
     "expr": "sum(rate(haproxy_frontend_requests_denied_total{frontend=~\"$frontend\",ident=\"$ident\"}[5m])) by (frontend)",
     "legendFormat": "Front request denied - {{frontend}}"
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_redispatch_warnings_total{backend=~\"$backend\",ident=\"$ident\"}[5m])) by (backend)",
     "legendFormat": "Back redispatch warnings + {{backend}}"
    },
    {
     "expr": "sum(rate(haproxy_backend_retry_warnings_total{backend=~\"$backend\",ident=\"$ident\"}[5m])) by (backend)",
     "legendFormat": "Back retry warnings + {{backend}}"
    },
    {
     "expr": "sum(rate(haproxy_backend_response_errors_total{backend=~\"$backend\",ident=\"$ident\"}[5m])) by (backend)",
     "legendFormat": "Back response errors + {{backend}}"
    },
    {
     "expr": "sum(haproxy_backend_current_queue{backend=~\"$backend\",ident=\"$host\"}) by (backend)",
     "legendFormat": "Back queued requests + {{backend}}"
    },
    {
     "expr": "sum(rate(haproxy_backend_connection_errors_total{backend=~\"$backend\", ident=\"$ident\"}[5m])) by (backend)",
     "legendFormat": "Back conn errors + {{backend}}"
    }
   ]
  }
 ]
}