{
 "title": "NSQ Metrics",
 "tags": [ "nsq metrics" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "NSQ Topic Message Depth",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "nsq_topic_depth", "legendFormat": "Topic: {{topic}}" }
   ]
  },
  {
   "title": "NSQ Channel Message Depth",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "nsq_channel_depth",
     "legendFormat": "Channel: {{channel}} ({{topic}})"
    }
   ]
  },
  {
   "title": "NSQ Topic Messages/s",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(nsq_topic_message_count[5m])",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "NSQ Channel Inflight/Deferred",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "nsq_channel_inflight_count", "legendFormat": "Inflight: {{channel}}" },
    { "expr": "nsq_channel_deferred_count", "legendFormat": "Deferred: {{channel}}" }
   ]
  }
 ]
}