{
 "title": "Categraf Self Monitoring Dashboard",
 "tags": [
  "categraf self monitoring dashboard"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Categraf Queue Size",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "categraf_current_queue_size", "legendFormat": "{{agent_hostname}}" }
   ]
  },
  {
   "title": "Categraf Enqueue Rate",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(categraf_metrics_enqueue_sum[5m])",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Categraf Memory (RSS Bytes)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~'.*categraf.*'}",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Categraf Goroutines",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "go_goroutines{job=~'.*categraf.*'}",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  }
 ]
}