before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

snapshot:
  name_template: '{{ .Tag }}'
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true

builds:
  - id: linux-arm64
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X flashcat.cloud/categraf/config.Version={{ .Tag }}-{{.Commit}}
  - id: linux-amd64
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X flashcat.cloud/categraf/config.Version={{ .Tag }}-{{.Commit}}
  - id: linux-amd64-cgo
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - enterprise
      - arppacket
    ldflags:
      - -s -w
      - -X flashcat.cloud/categraf/config.Version={{ .Tag }}-{{.Commit}}
  - id: windows
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X flashcat.cloud/categraf/config.Version={{ .Tag }}-{{.Commit}}

archives:
  - id: categraf
    rlcp: true
    builds:
      - linux-amd64-cgo
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}-with-cgo-plugin"
    wrap_in_directory: true
    files:
      - conf/*
  - id: categraf-common
    rlcp: true
    builds:
      - linux-amd64
      - linux-arm64
      - windows
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - conf/*

release:
  github:
    owner: flashcatcloud
    name: categraf
  name_template: "v{{ .Version }}"

dockers:
  - image_templates:
      - flashcatcloud/categraf:{{ .Tag }}-amd64
    goos: linux
    goarch: amd64
    ids:
      - linux-amd64
    dockerfile: docker/Dockerfile.goreleaser
    extra_files:
      - docker/entrypoint.sh
      - docker/nsswitch.conf
      - conf/config.toml
      - conf/logs.toml
      - conf/input.cpu/cpu.toml
      - conf/input.mem/mem.toml
      - conf/input.disk/disk.toml
      - conf/input.diskio/diskio.toml
      - conf/input.kernel/kernel.toml
      - conf/input.linux_sysctl_fs/linux_sysctl_fs.toml
      - conf/input.system/system.toml
      - conf/input.kernel_vmstat/kernel_vmstat.toml
      - conf/input.netstat/netstat.toml
      - conf/input.net/net.toml
      - conf/input.docker/docker.toml
      - conf/input.kubernetes/kubernetes.toml
      - conf/input.processes/processes.toml
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"

  - image_templates:
      - flashcatcloud/categraf:{{ .Tag }}-arm64v8
    goos: linux
    goarch: arm64
    ids:
      - linux-arm64
    dockerfile: docker/Dockerfile.goreleaser.arm64
    extra_files:
      - docker/entrypoint.sh
      - docker/nsswitch.conf
      - conf/config.toml
      - conf/logs.toml
      - conf/input.cpu/cpu.toml
      - conf/input.mem/mem.toml
      - conf/input.disk/disk.toml
      - conf/input.diskio/diskio.toml
      - conf/input.kernel/kernel.toml
      - conf/input.linux_sysctl_fs/linux_sysctl_fs.toml
      - conf/input.system/system.toml
      - conf/input.kernel_vmstat/kernel_vmstat.toml
      - conf/input.netstat/netstat.toml
      - conf/input.net/net.toml
      - conf/input.docker/docker.toml
      - conf/input.kubernetes/kubernetes.toml
      - conf/input.processes/processes.toml
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:

  - name_template: flashcatcloud/categraf:{{ .Tag }}
    image_templates:
      - flashcatcloud/categraf:{{ .Tag }}-amd64
      - flashcatcloud/categraf:{{ .Tag }}-arm64v8

  - name_template: flashcatcloud/categraf:latest
    image_templates:
      - flashcatcloud/categraf:{{ .Tag }}-amd64
      - flashcatcloud/categraf:{{ .Tag }}-arm64v8
