before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

snapshot:
  name_template: '{{ .Tag }}'
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true

builds:
  - id: build
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      #- -s -w
      - -X flashcat.cloud/categraf/config.Version={{ .Tag }}-{{.Commit}}

archives:
  - id: categraf
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - conf/*

release:
  github:
    owner: kongfei605 
    name: categraf
  name_template: "v{{ .Version }}"

dockers:
  - image_templates:
      - flashcatcloud/categraf:amd64-{{ .Tag }}
    goos: linux
    goarch: amd64
    ids:
      - build
    dockerfile: docker/Dockerfile.goreleaser
    extra_files:
      - docker/entrypoint.sh
      - conf/config.toml
      - conf/logs.toml
      - conf/input.cpu/cpu.toml
      - conf/input.mem/mem.toml
      - conf/input.disk/disk.toml
      - conf/input.diskio/diskio.toml
      - conf/input.kernel/kernel.toml
      - conf/input.linux_sysctl_fs/linux_sysctl_fs.toml
      - conf/input.system/system.toml
      - conf/input.kernel_vmstat/kernel_vmstat.toml
      - conf/input.netstat/netstat.toml
      - conf/input.net/net.toml
      - conf/input.docker/docker.toml
      - conf/input.kubernetes/kubernetes.toml
      - conf/input.processes/processes.toml
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"

docker_manifests:
  - name_template: flashcatcloud/categraf:{{ .Tag }}
    image_templates:
      - flashcatcloud/categraf:amd64-{{ .Tag }}

  - name_template: flashcatcloud/categraf:latest
    image_templates:
      - flashcatcloud/categraf:amd64-{{ .Tag }}
