version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

snapshot:
  version_template: '{{ .Tag }}'

checksum:
  name_template: 'checksums.txt'
changelog:
  use: github-native

builds:
  - id: linux-arm64
    main: ./
    binary: categraf
    env: &env_nocgo
      - CGO_ENABLED=0
      - GODEBUG=x509negativeserial=1
    goos:
      - linux
    goarch:
      - arm64
    ldflags: &ldflags_default
      - -s -w
      - -X flashcat.cloud/categraf/config.Version={{ .Tag }}-{{.Commit}}
  - id: linux-amd64
    main: ./
    binary: categraf
    env: *env_nocgo
    goos:
      - linux
    goarch:
      - amd64
    ldflags: *ldflags_default
  - id: linux-amd64-cgo
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    tags:
      - dcgm
    ldflags:
      - -s -w
      - -X flashcat.cloud/categraf/config.Version={{ .Tag }}-{{.Commit}}
      - -extldflags "-Wl,-z,lazy"
  - id: linux-slim
    main: ./
    binary: categraf
    env: *env_nocgo
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - no_ibex
      - no_traces
      - no_logs
      - no_prometheus
    ldflags: &ldflags_slim
      - -s -w
      - -X flashcat.cloud/categraf/config.Version=slim-{{ .Tag }}-{{.Commit}}

  - id: linux-metrics-agent
    main: ./
    binary: categraf
    env: *env_nocgo
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    tags:
      - no_ibex
      - no_traces
      - no_logs
    ldflags: *ldflags_slim

  - id: windows
    main: ./
    binary: categraf
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: *ldflags_default

archives:
  - id: categraf
    ids:
      - linux-amd64-cgo
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}-with-cgo-plugin"
    wrap_in_directory: true
    files:
      - conf/*

  - id: categraf-linux-amd64
    ids:
      - linux-amd64
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - conf/*
      - src: embedded/linux-amd64/*.tar.gz
        dst: embedded/huatuo.tar.gz

  - id: categraf-linux-arm64
    ids:
      - linux-arm64
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - conf/*
      - src: embedded/linux-arm64/*.tar.gz
        dst: embedded/huatuo.tar.gz

  - id: categraf-common-win
    ids:
      - windows
    formats:
      - zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - conf/*
      - scripts/win_run.bat

  - id: categraf-slim
    ids:
      - linux-slim
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}-slim-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
    files:
      - conf/*

release:
  github:
    owner: flashcatcloud
    name: categraf
  name_template: "v{{ .Version }}"

dockers:
  - &base_docker_config
    use: buildx
    goos: linux
    dockerfile: docker/Dockerfile.goreleaser
    image_templates:
      - flashcatcloud/categraf:{{ .Tag }}-amd64
    goarch: amd64
    ids:
      - linux-amd64
    extra_files:
      - docker/entrypoint.sh
      - docker/nsswitch.conf
      - conf/config.toml
      - conf/logs.toml
      - conf/input.cpu/cpu.toml
      - conf/input.mem/mem.toml
      - conf/input.disk/disk.toml
      - conf/input.diskio/diskio.toml
      - conf/input.kernel/kernel.toml
      - conf/input.linux_sysctl_fs/linux_sysctl_fs.toml
      - conf/input.system/system.toml
      - conf/input.kernel_vmstat/kernel_vmstat.toml
      - conf/input.netstat/netstat.toml
      - conf/input.net/net.toml
      - conf/input.processes/processes.toml
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--provenance=false"

  - <<: *base_docker_config
    image_templates:
      - flashcatcloud/categraf:slim-{{ .Tag }}-amd64
    goarch: amd64
    ids:
      - linux-slim
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--provenance=false"

  - <<: *base_docker_config
    image_templates:
      - flashcatcloud/categraf:{{ .Tag }}-arm64v8
    goarch: arm64
    ids:
      - linux-arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--provenance=false"

  - <<: *base_docker_config
    image_templates:
      - flashcatcloud/categraf:slim-{{ .Tag }}-arm64v8
    goarch: arm64
    ids:
      - linux-metrics-agent
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--provenance=false"

docker_manifests:
  - name_template: flashcatcloud/categraf:{{ .Tag }}
    image_templates:
      - flashcatcloud/categraf:{{ .Tag }}-amd64
      - flashcatcloud/categraf:{{ .Tag }}-arm64v8

  - name_template: flashcatcloud/categraf:slim-{{ .Tag }}
    image_templates:
      - flashcatcloud/categraf:slim-{{ .Tag }}-amd64
      - flashcatcloud/categraf:slim-{{ .Tag }}-arm64v8

  - name_template: flashcatcloud/categraf:latest
    image_templates:
      - flashcatcloud/categraf:{{ .Tag }}-amd64
      - flashcatcloud/categraf:{{ .Tag }}-arm64v8

announce:
  webhook:
    enabled: true
    skip_tls_verify: true
    message_template: '{ "text": {"content": "{{ .ProjectName }} {{.Tag}} is out! Check it out at {{ .ReleaseURL }}"}, "msgtype":"text"}'
    content_type: "application/json"
    endpoint_url: "https://oapi.dingtalk.com/robot/send?access_token={{ .Env.DING_TALK_TOKEN }}"
    # headers:
    #   Authorization: "Bearer <token>"
    headers:
      User-Agent: "goreleaser"
