{
 "title": "Kafka Key Metrics",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kafka_java_runtime_Uptime, cluster)"
    }
   },
   {
    "name": "ident",
    "label": "ident",
    "query": {
     "query": "label_values(kafka_java_runtime_Uptime{cluster=\"$cluster\"}, ident)"
    }
   }
  ]
 },
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(kafka_java_runtime_Uptime{cluster=\"$cluster\", ident=~\"$ident\"})/1000"
    }
   ]
  },
  {
   "title": "HeapMemoryUsage(Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_java_memory_HeapMemoryUsage_used{cluster=\"$cluster\", ident=~\"$ident\"}",
     "legendFormat": "{{ident}}"
    }
   ]
  },
  {
   "title": "HeapMemoryUsage(%)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "kafka_java_memory_HeapMemoryUsage_used{cluster=\"$cluster\", ident=~\"$ident\"}/kafka_java_memory_HeapMemoryUsage_max{cluster=\"$cluster\", ident=~\"$ident\"}",
     "legendFormat": "{{ident}}"
    }
   ]
  },
  {
   "title": "GC Rate(G1 Young)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "irate(kafka_java_garbage_collector_CollectionCount{cluster=\"$cluster\", ident=~\"$ident\", name=~\"G1 Young Generation\"}[1m])",
     "legendFormat": "{{ident}} {{name}}"
    }
   ]
  },
  {
   "title": "Threads Sum",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_java_threading_ThreadCount{cluster=\"$cluster\", ident=~\"$ident\"})"
    }
   ]
  },
  {
   "title": "MemoryPoolUsage(Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 13, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "kafka_java_memory_pool_Usage_used{cluster=\"$cluster\", ident=~\"$ident\"}",
     "legendFormat": "{{ident}} {{name}}"
    }
   ]
  },
  {
   "title": "GC Rate(G1 Old)",
   "type": "timeseries",
   "description": "Full GC",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "irate(kafka_java_garbage_collector_CollectionCount{cluster=\"$cluster\", ident=~\"$ident\", name=~\"G1 Old Generation\"}[1m])",
     "legendFormat": "{{ident}} {{name}}"
    }
   ]
  },
  {
   "title": "LastGC Use MS",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "kafka_java_last_garbage_collection_LastGcInfo_duration{cluster=\"$cluster\", ident=~\"$ident\"}",
     "legendFormat": "{{ident}}"
    }
   ]
  },
  {
   "title": "YoungGC Use MS/Second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(kafka_java_garbage_collector_CollectionTime{cluster=\"$cluster\", ident=~\"$ident\", name=\"G1 Young Generation\"}[1m])",
     "legendFormat": "{{ident}}"
    }
   ]
  },
  {
   "title": "FullGC Use MS/Second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "irate(kafka_java_garbage_collector_CollectionTime{cluster=\"$cluster\", ident=~\"$ident\", name=\"G1 Old Generation\"}[1m])",
     "legendFormat": "{{ident}}"
    }
   ]
  },
  { "title": "Kafka", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "活跃控制器数量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_ActiveControllerCount_Value{cluster=\"$cluster\", ident=~\"$ident\"})"
    }
   ]
  },
  {
   "title": "非同步分区数量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_cluster_UnderReplicatedPartitions{cluster=\"$cluster\", ident=~\"$ident\"})"
    }
   ]
  },
  {
   "title": "离线分区数量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_OfflinePartitionsCount_Value{cluster=\"$cluster\", ident=~\"$ident\"})"
    }
   ]
  },
  {
   "title": "离线日志目录数量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_logmanager_OfflineLogDirectoryCount{cluster=\"$cluster\", ident=~\"$ident\"})"
    }
   ]
  },
  {
   "title": "Panel 17",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(kafka_replica_manager_PartitionCount_Value{cluster=\"$cluster\", ident=~\"$ident\"}) by (ident)",
     "legendFormat": "分区数量"
    },
    {
     "expr": "sum(kafka_replica_manager_LeaderCount_Value{cluster=\"$cluster\", ident=~\"$ident\"}) by (ident)",
     "legendFormat": "主分区数量"
    },
    {
     "expr": "sum(irate(kafka_topic_BytesInPerSec_Count{cluster=\"$cluster\", ident=~\"$ident\"}[5m])) by (ident)",
     "legendFormat": "入方向字节/秒"
    },
    {
     "expr": "sum(irate(kafka_topic_BytesOutPerSec_Count{cluster=\"$cluster\", ident=~\"$ident\"}[5m])) by (ident)",
     "legendFormat": "出方向字节/秒"
    },
    {
     "expr": "sum(irate(kafka_topics_MessagesInPerSec_Count{cluster=\"$cluster\", ident=~\"$ident\"}[5m])) by (ident)",
     "legendFormat": "入消息/秒"
    }
   ]
  },
  {
   "title": "Topic数据预计还需消费多久",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(kafka_consumer_lag_millis{cluster=\"$cluster\", ident=~\"$ident\"}) by (consumergroup, topic, partition)"
    }
   ]
  }
 ]
}