[[instances]]

# https://statuslist.app/apache/apache-status-page-simple-setup-guide/
# scrape_uri = "http://localhost/server-status/?auto"
# host_override = ""
# insecure = false
# custom_headers = {}
# level: debug,info,warn,error
# log_level = "info"
