{
 "title": "Redis Overview by instance",
 "tags": [
  "categraf",
  "grafana",
  "Redis",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(redis_uptime_in_seconds,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Panel 2", "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 } },
  {
   "title": "Redis Uptime Days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(redis_uptime_in_seconds{instance=~\"$instance\"})/3600/24"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redis_connected_clients{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_used_memory{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Max Memory Limit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_maxmemory{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Fragmentation Ratio",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_mem_fragmentation_ratio{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Commands Executed / sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(redis_total_commands_processed{instance=~\"$instance\"}[5m])"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits{instance=~\"$instance\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses{instance=~\"$instance\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Top Commands",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "topk(5, irate(redis_cmdstat_calls{instance=~\"$instance\"} [1m]))",
     "legendFormat": "{{command}}"
    }
   ]
  },
  { "title": "Keys", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Items per DB",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum (redis_keyspace_keys{instance=~\"$instance\"}) by (db)",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(redis_keyspace_keys{instance=~\"$instance\"}) - sum(redis_keyspace_expires{instance=~\"$instance\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum(redis_keyspace_expires{instance=~\"$instance\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  { "title": "Network and CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(redis_total_net_input_bytes{instance=~\"$instance\"}[5m]))",
     "legendFormat": "input"
    },
    {
     "expr": "sum(rate(redis_total_net_output_bytes{instance=~\"$instance\"}[5m]))",
     "legendFormat": "output"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate (redis_used_cpu_sys{instance=~\"$instance\"}[1m]) * 100 + irate (redis_used_cpu_user{instance=~\"$instance\"}[1m]) * 100"
    }
   ]
  }
 ]
}