{
 "title": "ElasticSearch by Categraf",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(elasticsearch_up, cluster)"
    }
   },
   {
    "name": "node_host",
    "label": "node_host",
    "query": {
     "query": "label_values(elasticsearch_jvm_uptime_in_millis{cluster=\"$cluster\"}, node_host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(elasticsearch_cluster_health_status_code{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(elasticsearch_cluster_health_number_of_data_nodes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Util Percent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_process_cpu_percent{cluster=\"$cluster\", node_host=~\"$node_host\"})"
    }
   ]
  },
  {
   "title": "JVM Heap Util Percent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_jvm_mem_heap_used_percent{cluster=\"$cluster\", node_host=~\"$node_host\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_number_of_pending_tasks{cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "Breakers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Tripped for breakers",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum({__name__=~\"elasticsearch_breakers_.+_tripped\", cluster=\"$cluster\", node_host=~\"$node_host\"}) by (node_host)"
    }
   ]
  },
  {
   "title": "Estimated size in bytes of breaker",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "{__name__=~\"elasticsearch_breakers_.+_size_in_bytes\", cluster=\"$cluster\", node_host=~\"$node_host\"}",
     "legendFormat": "{{__name__}} {{node_host}}"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Active shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Active primary shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_active_primary_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Initializing shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_initializing_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Relocating shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_relocating_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Delayed Unassigned shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_delayed_unassigned_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Unassigned shards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(elasticsearch_cluster_health_unassigned_shards{cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "GC counts / second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collectors_old_collection_count{cluster=\"$cluster\", node_host=~\"$node_host\"}[5m])",
     "legendFormat": "old gc {{node_host}}"
    },
    {
     "expr": "irate(elasticsearch_jvm_gc_collectors_young_collection_count{cluster=\"$cluster\", node_host=~\"$node_host\"}[5m])",
     "legendFormat": "young gc {{node_host}}"
    }
   ]
  },
  {
   "title": "GC time in millis",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "irate(elasticsearch_jvm_gc_collectors_old_collection_time_in_millis{cluster=\"$cluster\", node_host=~\"$node_host\"}[5m])",
     "legendFormat": "old gc {{node_host}}"
    },
    {
     "expr": "irate(elasticsearch_jvm_gc_collectors_young_collection_time_in_millis{cluster=\"$cluster\", node_host=~\"$node_host\"}[5m])",
     "legendFormat": "young gc {{node_host}}"
    }
   ]
  },
  {
   "title": "Yong Used(Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{__name__=~\"elasticsearch_jvm_mem_pools_young_used_in_bytes\", cluster=\"$cluster\", node_host=~\"$node_host\"}",
     "legendFormat": "{{__name__}} {{node_name}}"
    }
   ]
  },
  {
   "title": "Old Used(Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "{__name__=~\"elasticsearch_jvm_mem_pools_old_used_in_bytes\", cluster=\"$cluster\", node_host=~\"$node_host\"}",
     "legendFormat": "{{__name__}} {{node_name}}"
    }
   ]
  },
  {
   "title": "Committed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "{__name__=~\"elasticsearch_jvm_mem_.+_committed_in_bytes\", cluster=\"$cluster\", node_host=~\"$node_host\"}",
     "legendFormat": "{{__name__}} {{node_name}}"
    }
   ]
  },
  { "title": "Translog", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Total translog operations",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_translog_operations{cluster=\"$cluster\", node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Total translog size in bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_translog_size_in_bytes{cluster=\"$cluster\", node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  { "title": "Disk and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Disk usage %",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "1-(elasticsearch_fs_total_available_in_bytes{cluster=\"$cluster\",node_host=~\"$node_host\"}/elasticsearch_fs_total_total_in_bytes{cluster=\"$cluster\",node_host=~\"$node_host\"})",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_tx_size_in_bytes{cluster=\"$cluster\",node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}: sent"
    },
    {
     "expr": "-irate(elasticsearch_transport_rx_size_in_bytes{cluster=\"$cluster\",node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}: received"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Documents count on node",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "elasticsearch_indices_docs_count{cluster=\"$cluster\", node_host=~\"$node_host\"}",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Documents indexed rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\",node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Documents deleted rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_docs_deleted{cluster=\"$cluster\",node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Documents merged rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total_docs{cluster=\"$cluster\",node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Documents merged bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_size_in_bytes{cluster=\"$cluster\",node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  { "title": "Times", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Query time(Unit: ms)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_search_query_time_in_millis{cluster=\"$cluster\",node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Indexing time(Unit: ms)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_time_in_millis{cluster=\"$cluster\",node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Merging time(Unit: ms)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_merges_total_time_in_millis{cluster=\"$cluster\",node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Indexing throttle time(Unit: ms)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_throttle_time_in_millis{cluster=\"$cluster\",node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  { "title": "Thread Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Thread Pool operations rejected",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "irate\n(label_replace({__name__=~\"elasticsearch_thread_pool_(.*)_rejected\", cluster=\"$cluster\", node_host=~\"$node_host\"}, \"type\", \"$1\", \"__name__\", \"elasticsearch_thread_pool_(.*)_rejected\")[5m:])",
     "legendFormat": "{{node_host}}: {{type}}"
    }
   ]
  },
  {
   "title": "Thread Pool threads active",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 50 },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"elasticsearch_thread_pool_(.*)_active\", cluster=\"$cluster\", node_host=~\"$node_host\"}, \"type\", \"$1\", \"__name__\", \"elasticsearch_thread_pool_(.*)_active\")",
     "legendFormat": "{{node_host}}: {{type}}"
    }
   ]
  },
  {
   "title": "Thread Pool threads queued",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"elasticsearch_thread_pool_(.*)_queue\", cluster=\"$cluster\", node_host=~\"$node_host\"}, \"type\", \"$1\", \"__name__\", \"elasticsearch_thread_pool_(.*)_queue\")",
     "legendFormat": "{{node_host}}: {{type}}"
    }
   ]
  },
  {
   "title": "Thread Pool operations completed",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 50 },
   "targets": [
    {
     "expr": "irate\n(label_replace({__name__=~\"elasticsearch_thread_pool_(.*)_completed\", cluster=\"$cluster\", node_host=~\"$node_host\"}, \"type\", \"$1\", \"__name__\", \"elasticsearch_thread_pool_(.*)_completed\")[5m:])",
     "legendFormat": "{{node_host}}: {{type}}"
    }
   ]
  },
  { "title": "Caches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Field data memory size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "elasticsearch_indices_fielddata_memory_size_in_bytes{cluster=\"$cluster\", node_host=~\"$node_host\"}",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Field data evictions",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 55 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_fielddata_evictions{cluster=\"$cluster\", node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Query cache size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 55 },
   "targets": [
    {
     "expr": "elasticsearch_indices_query_cache_memory_size_in_bytes{cluster=\"$cluster\", node_host=~\"$node_host\"}",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Query cache evictions",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_query_cache_evictions{cluster=\"$cluster\", node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Request cache evictions",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 55 },
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_request_cache_evictions{cluster=\"$cluster\", node_host=~\"$node_host\"}[5m])",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  { "title": "Segments", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Count of index segments",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_count{cluster=\"$cluster\", node_host=~\"$node_host\"}",
     "legendFormat": "{{node_host}}"
    }
   ]
  },
  {
   "title": "Current memory size of segments in bytes",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "elasticsearch_indices_segments_memory_in_bytes{cluster=\"$cluster\", node_host=~\"$node_host\"}",
     "legendFormat": "{{node_host}}"
    }
   ]
  }
 ]
}