{
 "title": "XSKY Storage Cluster",
 "tags": [ "xsky storage cluster" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "OSS Bucket Used Size",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "xskyapi_oss_bucket_used_size", "legendFormat": "{{name}} @ {{server}}" }
   ]
  },
  {
   "title": "DFS Quota",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "xskyapi_dfs_quota", "legendFormat": "{{name}} @ {{server}}" }
   ]
  },
  {
   "title": "Block Volume Used Size",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "xskyapi_block_volume_used_size", "legendFormat": "{{name}} @ {{server}}" }
   ]
  }
 ]
}