# # collect interval
#interval = 15

[[instances]]
## An array of Nginx stub_status URI to gather stats.
#url = "http://127.0.0.1:8171/api/topics"

## append some labels for series
#labels = { region="shanghai", product="nsq" }

## interval = global.interval * interval_times
#interval_times = 1
