{
 "title": "Tomcat - 模板",
 "tags": [
  "categraf",
  "grafana",
  "Categraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic Bytes / Second",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(tomcat_connector_bytes_sent{instance=\"$instance\"}[1m])",
     "legendFormat": "sent"
    },
    {
     "expr": "rate(tomcat_connector_bytes_received{instance=\"$instance\"}[1m])",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Request count / Second",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(tomcat_connector_request_count{instance=\"$instance\"}[1m])",
     "legendFormat": "tomcat_connector_request_count"
    },
    {
     "expr": "rate(tomcat_connector_error_count{instance=\"$instance\"}[1m])",
     "legendFormat": "tomcat_connector_error_count"
    }
   ]
  },
  {
   "title": "Tread",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "tomcat_connector_max_threads{instance=\"$instance\"}",
     "legendFormat": "max_threads"
    },
    {
     "expr": "tomcat_connector_current_thread_count{instance=\"$instance\"}",
     "legendFormat": "current_thread_count"
    },
    {
     "expr": "tomcat_connector_current_threads_busy{instance=\"$instance\"}",
     "legendFormat": "current_threads_busy"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "rate(tomcat_connector_processing_time{instance=\"$instance\"}[1m])",
     "legendFormat": "{{name}}-processing_time"
    }
   ]
  },
  { "title": "mem used", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "tomcat_jvm_memory_max{instance=\"$instance\"}",
     "legendFormat": "max"
    },
    {
     "expr": "tomcat_jvm_memory_total{instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "tomcat_jvm_memory_free{instance=\"$instance\"}",
     "legendFormat": "free"
    }
   ]
  },
  { "title": "memorypool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Used",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tomcat_jvm_memorypool_used{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Max",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tomcat_jvm_memorypool_max{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Committed",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tomcat_jvm_memorypool_committed{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Init",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "tomcat_jvm_memorypool_init{instance=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}