{
 "title": "Consul",
 "tags": [ "consul" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Consul Up",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 4 },
   "targets": [
    { "expr": "consul_up", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Consul Catalog Services",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 4 },
   "targets": [
    { "expr": "consul_catalog_services", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Consul LAN Members",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "consul_serf_lan_members", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Consul Raft Peers",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "consul_raft_peers", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Consul Health Service Status (Critical)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "consul_health_service_status{status=\"critical\"}",
     "legendFormat": "{{service_name}} on {{node}}"
    }
   ]
  }
 ]
}