{
 "title": "ClickHouse",
 "tags": [ "clickhouse" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "ClickHouse Insert Queries",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(clickhouse_events_insert_query[5m])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "ClickHouse Select Queries",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(clickhouse_events_select_query[5m])",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "ClickHouse Memory Tracking",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "clickhouse_metrics_memory_tracking",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "ClickHouse Max Part Count",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "clickhouse_asynchronous_metrics_max_part_count_for_partition",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}