{
 "title": "System Netstat Metrics",
 "tags": [ "system netstat metrics" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "TCP Established Connections",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "netstat_tcp_established", "legendFormat": "{{agent_hostname}}" }
   ]
  },
  {
   "title": "TCP Time-Wait Connections",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "netstat_tcp_time_wait", "legendFormat": "{{agent_hostname}}" }
   ]
  },
  {
   "title": "TCP Close-Wait Connections",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "netstat_tcp_close_wait", "legendFormat": "{{agent_hostname}}" }
   ]
  },
  {
   "title": "UDP Sockets",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "netstat_udp_socket", "legendFormat": "{{agent_hostname}}" }
   ]
  }
 ]
}