# Gathers information about processes that running under supervisor using XML-RPC API
[[instances]]
## Url of supervisor's XML-RPC endpoint if basic auth enabled in supervisor http server,
## than you have to add credentials to url (ex. http://login:pass@localhost:9001/RPC2)
# url = "http://login:pass@localhost:9001/RPC2", eg: url = "http://localhost:9001/RPC2"
url =""
## With settings below you can manage gathering additional information about processes
## If both of them empty, then all additional information will be collected.
## Currently supported supported additional metrics are: pid, rc
# metrics_include = []
# metrics_exclude = ["pid", "rc"]