{
 "title": "Nginx Upstream",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "target",
    "label": "target",
    "query": {
     "query": "label_values(nginx_upstream_check_status_code,target)"
    }
   },
   {
    "name": "upstream",
    "label": "upstream",
    "query": {
     "query": "label_values(nginx_upstream_check_status_code,upstream)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_upstream_check_status_code{target=\"$target\"}"
    }
   ]
  },
  {
   "title": "Rise check",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_upstream_check_rise{target=\"$target\",upstream=\"$upstream\"}"
    }
   ]
  },
  {
   "title": "Fall Check",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_upstream_check_fall{target=\"$target\",upstream=\"$upstream\"}"
    }
   ]
  }
 ]
}