### k8s 1.24及以上版本需要手动创建secret
apiVersion: v1
kind: Secret
metadata:
  name: categraf-secret
  annotations:
    kubernetes.io/service-account.name: "categraf-serviceaccount"
type: kubernetes.io/service-account-token
