name: Bug report
description: Report a bug encountered while running categraf
labels: ["kind/bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking time to fill out this bug report! 
        Please redirect any questions about categraf usage to our [Wechat Group](https://n9e.github.io/images/wx.jpg) we have a lot of talented community members there who could help answer your question more quickly.
  - type: textarea
    id: config
    attributes:
      label: Relevant config.toml
      description: Place config in the toml code section. This will be automatically formatted into toml, so no need for backticks.
      render: toml
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs from categraf
      description: Please include the categraf logs, ideally with `--debug` used.
      render: text
    validations:
      required: true
  - type: input
    id: system-info
    attributes:
      label: System info
      description: Include categraf version, operating system, and other relevant details
      placeholder: ex. categraf 0.1.0, Ubuntu 20.04, Docker 20.10.8
    validations:
      required: true
  - type: textarea
    id: docker
    attributes:
      label: Docker
      description: If your bug involves third party dependencies or services, it can be very helpful to provide a Dockerfile or docker-compose.yml that reproduces the environment you're testing against.
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Describe the steps to reproduce the bug.
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen when you performed the above steps.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Describe what actually happened when you performed the above steps.
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: Include gist of relevant config, logs, etc.
    validations:
      required: false
