{
 "title": "Net Response 探测",
 "tags": [
  "categraf",
  "net_response"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "target",
    "label": "target",
    "query": {
     "query": "label_values(net_response_result_code, target)"
    }
   }
  ]
 },
 "panels": [
  { "title": "全局巡检", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "所有 Target 健康状态",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(net_response_result_code) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "所有 Target 响应时间",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(net_response_response_time) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Target 当前明细",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(net_response_result_code) by (target)",
     "legendFormat": "result_code"
    },
    {
     "expr": "max(net_response_response_time) by (target)",
     "legendFormat": "latency_s"
    }
   ]
  },
  { "title": "单 Target 详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "当前健康状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(net_response_result_code{target=\"$target\"})",
     "legendFormat": "result_code"
    }
   ]
  },
  {
   "title": "当前响应时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(net_response_response_time{target=\"$target\"})",
     "legendFormat": "latency_s"
    }
   ]
  },
  {
   "title": "响应时间趋势",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "net_response_response_time{target=\"$target\"}",
     "legendFormat": "latency_s"
    }
   ]
  },
  {
   "title": "状态变化趋势",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "net_response_result_code{target=\"$target\"}",
     "legendFormat": "result_code"
    }
   ]
  }
 ]
}