{
 "title": "Categraf OracleDB Dashboard for Prometheus",
 "description": "Oracle 数据库大盘，通过 Categraf 采集器下的 Oracle 插件抓取数据库指标",
 "tags": [
  "categraf",
  "prometheus",
  "oracle"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "区域", "query": { "query": "label_values(oracle_up,region)" } },
   {
    "name": "instance",
    "label": "监控实例",
    "query": {
     "query": "label_values(oracle_up{region=~\"$region\"},instance)"
    }
   },
   {
    "name": "address",
    "label": "数据库实例",
    "query": {
     "query": "query_result(count by (address) (count_over_time(oracle_up{region=~\"$region\", instance=~\"$instance\"}[$__range])))"
    }
   },
   {
    "name": "total",
    "label": "汇总",
    "query": {
     "query": "query_result(count(oracle_up{region=~\"$region\"}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "资源总览 - 总数【${total}】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "数据库总览",
     "type": "table",
     "description": "数据库总览信息",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "oracle_env_running_time{region=\"$region\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "oracle_env_is_rac{region=\"$region\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "oracle_env_value{region=\"$region\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "oracle_env_vols{region=\"$region\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "oracle_up{region=\"$region\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "oracle_dataguard_exist_value{region=\"$region\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "oracle_dataguard_status_value{region=\"$region\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "监控实例：【${instance}】数据库实例：【${address}】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "数据库连接状态",
   "type": "stat",
   "description": "No data 表示 oracledb_exporter 进程宕掉或其他异常",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracle_up{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}"
    }
   ]
  },
  {
   "title": "RMAN备份",
   "type": "stat",
   "description": "No data 表示 oracledb_exporter 进程宕掉或其他异常",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracle_rman_status_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}"
    }
   ]
  },
  {
   "title": "数据库可用性",
   "type": "state-timeline",
   "description": "No data 表示 oracledb_exporter 进程宕掉或其他异常",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 2 },
   "targets": [
    {
     "expr": "oracle_up{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "实时会话数",
   "type": "gauge",
   "description": "数据库实时会话信息",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(oracle_sessions_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\", status=~\"ACTIVE\"})",
     "legendFormat": "活跃会话"
    },
    {
     "expr": "sum(oracle_sessions_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"})",
     "legendFormat": "总会话"
    },
    {
     "expr": "sum(oracle_sessions_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}) / sum(oracle_parameter_sessions_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}) * 100",
     "legendFormat": "会话与限额百分比"
    }
   ]
  },
  {
   "title": "平均每秒耗时",
   "type": "timeseries",
   "description": "数据库每秒处理请求的总成本，用于判断数据库整体负载的高低",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "oracle_sysmetric_database_time_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"} / 100",
     "legendFormat": "DB_Time（单位：秒）"
    }
   ]
  },
  {
   "title": "每秒逻辑读",
   "type": "timeseries",
   "description": "数据库每秒发生的逻辑读次数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oracle_sysmetric_logical_reads_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "每秒逻辑读（单位：block）"
    }
   ]
  },
  {
   "title": "表空间",
   "type": "table",
   "description": "数据库表空间信息",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "oracle_tablespace_bytes{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oracle_tablespace_free{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "oracle_tablespace_max_bytes{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1- oracle_tablespace_free{address=~\"$address\", instance=\"$instance\", region=~\"$region\"} / oracle_tablespace_max_bytes{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "会话数",
   "type": "timeseries",
   "description": "数据库会话信息",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(oracle_sessions_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\", status=~\"ACTIVE\"})",
     "legendFormat": "活跃会话"
    },
    {
     "expr": "sum(oracle_sessions_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"})",
     "legendFormat": "总会话"
    }
   ]
  },
  {
   "title": "每秒用户数/事务数",
   "type": "timeseries",
   "description": "数据库每秒用户数/事务数",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "oracle_sysmetric_logons_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "活跃会话"
    },
    {
     "expr": "oracle_sysmetric_user_transaction_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "总会话"
    }
   ]
  },
  {
   "title": "数据库 IOPS",
   "type": "timeseries",
   "description": "数据库读写 IOPS",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "oracle_sysmetric_physical_read_total_io_requests_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "读 IOPS"
    },
    {
     "expr": "oracle_sysmetric_physical_write_total_io_requests_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"} + oracle_sysmetric_redo_writes_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "写 IOPS"
    },
    {
     "expr": "oracle_sysmetric_physical_read_total_io_requests_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"} + oracle_sysmetric_physical_write_total_io_requests_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"} + oracle_sysmetric_redo_writes_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "总 IOPS"
    }
   ]
  },
  {
   "title": "数据库 MBPS",
   "type": "timeseries",
   "description": "数据库每秒读写带宽MBPS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "oracle_sysmetric_physical_read_total_bytes_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"} / 1024 / 1024",
     "legendFormat": "每秒IO读（单位：MB）"
    },
    {
     "expr": "(oracle_sysmetric_physical_write_total_bytes_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"} + oracle_sysmetric_redo_generated_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}) / 1024 / 1024",
     "legendFormat": "每秒IO写（单位：MB）"
    },
    {
     "expr": "oracledb_sysmetric_physical_read_total_bytes_per_sec{address=~\"$address\", instance=\"$instance\", job=\"$job\"} / 1024 / 1024+ (oracledb_sysmetric_physical_write_total_bytes_per_sec{address=~\"$address\", instance=\"$instance\", job=\"$job\"} + oracledb_sysmetric_redo_generated_per_sec{address=~\"$address\", instance=\"$instance\", job=\"$job\"}) / 1024 / 1024",
     "legendFormat": "总读写（单位：MB）"
    }
   ]
  },
  {
   "title": "每秒接收/每秒发送",
   "type": "timeseries",
   "description": "代表 Oracle 实例通过 SQL*Net 协议从客户端接收/发送的数据总量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "rate(oracle_sysstat_bytes_received_via_sqlnet_from_client_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}[$__rate_interval]) / 1024 / 1024",
     "legendFormat": "From Client（单位：MB）"
    },
    {
     "expr": "rate(oracle_sysstat_bytes_sent_via_sqlnet_to_client_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}[$__rate_interval]) / 1024 / 1024",
     "legendFormat": "To Client（单位：MB）"
    }
   ]
  },
  {
   "title": "每秒 SQL 执行次数",
   "type": "timeseries",
   "description": "代表 Oracle 实例每秒执行多少条 SQL",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(oracle_sysstat_execute_count_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}[$__rate_interval])",
     "legendFormat": "每秒次数（单位：次）"
    }
   ]
  },
  {
   "title": "实例命中率【实时】",
   "type": "gauge",
   "description": "数据库实例实时命中率",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracle_sysmetric_buffer_cache_hit_ratio_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "Buffer Cache"
    },
    {
     "expr": "oracle_sysmetric_library_cache_hit_ratio_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "Library Cache"
    },
    {
     "expr": "oracle_sysmetric_row_cache_hit_ratio_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "Row Cache"
    },
    {
     "expr": "oracle_sysmetric_pga_cache_hit__value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "PGA Cache"
    },
    {
     "expr": "oracle_sysmetric_memory_sorts_ratio_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "Memory Sorts Ratio"
    },
    {
     "expr": "oracle_sysmetric_redo_allocation_hit_ratio_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "Redo Allocation"
    }
   ]
  },
  {
   "title": "实例命中率【平均】",
   "type": "gauge",
   "description": "数据库实例平均命中率",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(oracle_sysmetric_buffer_cache_hit_ratio_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}[$__rate_interval])",
     "legendFormat": "Buffer Cache"
    },
    {
     "expr": "avg_over_time(oracle_sysmetric_library_cache_hit_ratio_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}[$__rate_interval])",
     "legendFormat": "Library Cache"
    },
    {
     "expr": "avg_over_time(oracle_sysmetric_row_cache_hit_ratio_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}[$__rate_interval])",
     "legendFormat": "Row Cache"
    },
    {
     "expr": "avg_over_time(oracle_sysmetric_pga_cache_hit__value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}[$__rate_interval])",
     "legendFormat": "PGA Cache"
    },
    {
     "expr": "avg_over_time(oracle_sysmetric_memory_sorts_ratio_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}[$__rate_interval])",
     "legendFormat": "Memory Sorts Ratio"
    },
    {
     "expr": "avg_over_time(oracle_sysmetric_redo_allocation_hit_ratio_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}[$__rate_interval])",
     "legendFormat": "Redo Allocation"
    }
   ]
  },
  {
   "title": "恢复区空间使用率",
   "type": "timeseries",
   "description": "Oracle 数据库恢复区的总体空间使用百分比",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "oracle_recovery_file_dest_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "恢复区空间使用率",
   "type": "table",
   "description": "Oracle 数据库恢复区的总体空间使用百分比",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "oracle_recovery_file_dest_percent_space_used{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "等待事件【实时】",
   "type": "table",
   "description": "Oracle 数据库等待事件",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "oracle_events_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "redo 记录",
   "type": "table",
   "description": "Oracle 实例自启动以来产生的 REDO 总量（单位：字节）",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "oracle_env_redo_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "每秒 redo 大小",
   "type": "timeseries",
   "description": "Oracle 实例每秒产生的 REDO 总量",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "oracle_sysmetric_redo_generated_per_sec_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"} / 1024 / 1024",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "每秒 redo 大小",
   "type": "timeseries",
   "description": "Oracle 实例每秒产生的 REDO 总量",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "increase(oracle_env_redo_switch_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rman 备份信息",
   "type": "table",
   "description": "数据库启动的 rman 备份信息",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "oracle_rman_info_value{address=~\"$address\", instance=\"$instance\", region=~\"$region\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}