FROM --platform=$TARGETPLATFORM ubuntu:22.10

RUN  apt-get install -y tzdata

COPY docker/nsswitch.conf /etc/nsswitch.conf

COPY categraf  /usr/bin/categraf

COPY docker/entrypoint.sh /entrypoint.sh

COPY conf /etc/categraf/conf

CMD ["/entrypoint.sh"]
