FROM --platform=$TARGETPLATFORM ubuntu:24.04

COPY docker/nsswitch.conf /etc/nsswitch.conf

COPY categraf  /usr/bin/categraf

COPY docker/entrypoint.sh /entrypoint.sh

COPY conf /etc/categraf/conf

CMD ["/entrypoint.sh"]
