FROM --platform=$BUILDPLATFORM ubuntu:22.10

RUN echo 'hosts: files dns' >> /etc/nsswitch.conf

RUN set -ex && \
    mkdir -p /usr/bin /etc/categraf

COPY categraf  /usr/bin/categraf

COPY docker/entrypoint.sh /entrypoint.sh

COPY conf /etc/categraf/conf

CMD ["/entrypoint.sh"]
