FROM --platform=$TARGETPLATFORM flashcatcloud/ubuntu:24.04

ARG TARGETPLATFORM

RUN apt-get update \
    && apt-get install -y --no-install-recommends tini \
    && rm -rf /var/lib/apt/lists/*

COPY docker/nsswitch.conf /etc/nsswitch.conf

COPY --chmod=755 ${TARGETPLATFORM}/categraf /usr/bin/categraf

COPY --chmod=755 docker/entrypoint.sh /entrypoint.sh

COPY conf /etc/categraf/conf

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/entrypoint.sh"]
