{
 "title": "NATS Message Server",
 "tags": [ "nats message server" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "NATS Connections",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "nats_connections", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "NATS Subscriptions",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "nats_subscriptions", "legendFormat": "{{server}}" }
   ]
  },
  {
   "title": "NATS Message Throughput (Msgs/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(nats_in_msgs[5m])", "legendFormat": "In" },
    { "expr": "rate(nats_out_msgs[5m])", "legendFormat": "Out" }
   ]
  },
  {
   "title": "NATS Byte Throughput (Bytes/s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(nats_in_bytes[5m])", "legendFormat": "In" },
    { "expr": "rate(nats_out_bytes[5m])", "legendFormat": "Out" }
   ]
  },
  {
   "title": "NATS Slow Consumers",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    { "expr": "nats_slow_consumers", "legendFormat": "{{server}}" }
   ]
  }
 ]
}