package collector

func paramsInit(params map[string]string) {
	pathInit(params)
	arpCollectorInit(params)
	bcacheCollectorInit(params)
	cpuCollectorInit(params)
	diskstatsCollectorInit(params)
	ethtoolCollectorInit(params)
	filesystemCollectorInit(params)
	hwMonCollectorInit(params)
	ipvsCollectorInit(params)
	netClassCollectorInit(params)
	netDevCollectorInit(params)
	netStatCollectorInit(params)
	ntpCollectorInit(params)
	perfCollectorInit(params)
	powerSupplyClassCollectorInit(params)
	qdiscStatCollectorInit(params)
	raplCollectorInit(params)
	runitCollectorInit(params)
	statCollectorInit(params)
	supervisordCollectorInit(params)
	sysctlCollectorInit(params)
	systemdCollectorInit(params)
	tapestatsCollectorInit(params)
	textFileCollectorInit(params)
	vmStatCollectorInit(params)
	wifiCollectorInit(params)
	fileCollectorInit(params)
	crontabCollectorInit(params)
}
