# clickhouse output plugin, sending metrics to clickhouse
[metricshouse]
enable = false
debug = false
endpoints = ["10.1.1.7:9000", "10.1.1.8:9000"]
database = "default"
table = ""
username = ""
password = ""
dial_timeout = "1s"
max_open_conns = 10
max_idle_conns = 5
conn_max_lifetime = "1h"
queue_size = 100000
batch_size = 10000
idle_duration = "30s"
