{
 "title": "AWS RDS Telegraf",
 "tags": [
  "categraf",
  "grafana",
  "AWS",
  "Cloudwatch",
  "Telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "region",
    "label": "region",
    "query": {
     "query": "label_values(cloudwatch_aws_rds_cpu_utilization_average, region)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(cloudwatch_aws_rds_cpu_utilization_average{region=\"$region\"}, db_instance_identifier)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Common metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RDS CPU利用率(百分比)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds cpu 利用率平均值",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_cpu_utilization_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 数据库连接数",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 数据库连接平均值",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_database_connections_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 可用存储空间(MB/秒)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 可用存储空间平均值",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_free_storage_space_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 可用内存(MB)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 可用内存平均值",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_freeable_memory_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 写入IOPS(次数/秒)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds lvm 写入 iops 平均值",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_lvm_write_iops_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 读取IOPS(次数/秒)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 读取 iops 平均值",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_read_iops_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 写入吞吐量(MB/秒)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 写入吞吐量平均值",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_write_throughput_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 读取吞吐量(MB/秒)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 读取吞吐量平均值",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_read_throughput_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  { "title": "NetWork metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "RDS 网络接收吞吐量(MB/秒)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 网络接收吞吐量平均",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_network_receive_throughput_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 网络传输吞吐量(MB/秒)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 网络传输吞吐量平均值",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_network_transmit_throughput_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 写入延迟(毫秒)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 写入延迟平均值",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_write_latency_average{region=\"$region\",db_instance_identifier=\"$instance\"} * 1000",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 读取延迟(毫秒)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 读取延迟平均值",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_read_latency_average{region=\"$region\",db_instance_identifier=\"$instance\"} * 1000",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  { "title": "Additional metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "RDS 队列深度(数量)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 磁盘队列深度平均值",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_disk_queue_depth_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 二进制日志磁盘使用情况 (MB)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 二进制日志磁盘使用情况 (MB)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_bin_log_disk_usage_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 交换分区使用情况(MB)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 交换分区使用平均值",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_swap_usage_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  },
  {
   "title": "RDS 突发信用余额平均值(百分比)",
   "type": "timeseries",
   "description": "* Telegraf Gather AWS Cloudwatch RDS\n* cloudwatch aws rds 突发余额平均值",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_burst_balance_average{region=\"$region\",db_instance_identifier=\"$instance\"}",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  }
 ]
}