{
 "title": "MySQL Overview by instance",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(mysql_global_status_uptime, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Basic Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL Uptime Days",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{instance=~\"$instance\"}/3600/24",
     "legendFormat": "{{instance}} {{address}}"
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "stat",
   "description": "mysql_global_status_queries",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool",
   "type": "stat",
   "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{address}}"
    }
   ]
  },
  {
   "title": "Table Locks Waited(5min)",
   "type": "stat",
   "description": "**Table Locks**\n\nMySQL takes a number of different locks for varying reasons. In this graph we see how many Table level locks MySQL has requested from the storage engine. In the case of InnoDB, many times the locks could actually be row locks as it only takes table level locks in a few specific cases.\n\nIt is most useful to compare Locks Immediate and Locks Waited. If Locks waited is rising, it means you have lock contention. Otherwise, Locks Immediate rising and falling is normal activity.",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(mysql_global_status_table_locks_waited{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}}"
    }
   ]
  },
  {
   "title": "Slave Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {
     "expr": "mysql_slave_status_seconds_behind_master{instance=~\"$instance\"} - mysql_slave_status_sql_delay{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{address}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "MySQL Connections",
   "type": "timeseries",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{address}} Connections"
    }
   ]
  },
  {
   "title": "MySQL Connections Used Percent",
   "type": "timeseries",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{instance=~\"$instance\"}/mysql_global_variables_max_connections{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{address}}"
    }
   ]
  },
  {
   "title": "MySQL Client Thread Running",
   "type": "timeseries",
   "description": "Threads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_running{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{address}} Threads Running"
    }
   ]
  },
  {
   "title": "Max Used and Aborted Connections",
   "type": "timeseries",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "mysql_global_status_max_used_connections{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{address}} Max Used Connections"
    },
    {
     "expr": "rate(mysql_global_status_aborted_connects{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Aborted Connections"
    }
   ]
  },
  { "title": "Query Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "MySQL Temporary Objects",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_created_tmp_tables{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Created Tmp Tables"
    },
    {
     "expr": "rate(mysql_global_status_created_tmp_disk_tables{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Created Tmp Disk Tables"
    },
    {
     "expr": "rate(mysql_global_status_created_tmp_files{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Created Tmp Files"
    }
   ]
  },
  {
   "title": "MySQL Select Types",
   "type": "timeseries",
   "description": "**MySQL Select Types**\n\nAs with most relational databases, selecting based on indexes is more efficient than scanning an entire table's data. Here we see the counters for selects not done with indexes.\n\n* ***Select Scan*** is how many queries caused full table scans, in which all the data in the table had to be read and either discarded or returned.\n* ***Select Range*** is how many queries used a range scan, which means MySQL scanned all rows in a given range.\n* ***Select Full Join*** is the number of joins that are not joined on an index, this is usually a huge performance hit.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_select_full_join{ instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Select Full Join"
    },
    {
     "expr": "rate(mysql_global_status_select_full_range_join{ instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Select Full Range Join"
    },
    {
     "expr": "rate(mysql_global_status_select_range{ instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Select Range"
    },
    {
     "expr": "rate(mysql_global_status_select_range_check{ instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Select Range Check"
    },
    {
     "expr": "rate(mysql_global_status_select_scan{ instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Select Scan"
    }
   ]
  },
  {
   "title": "MySQL Sorts",
   "type": "timeseries",
   "description": "**MySQL Sorts**\n\nDue to a query's structure, order, or other requirements, MySQL sorts the rows before returning them. For example, if a table is ordered 1 to 10 but you want the results reversed, MySQL then has to sort the rows to return 10 to 1.\n\nThis graph also shows when sorts had to scan a whole table or a given range of a table in order to return the results and which could not have been sorted via an index.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_sort_rows{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Sort Rows"
    },
    {
     "expr": "rate(mysql_global_status_sort_range{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Sort Range"
    },
    {
     "expr": "rate(mysql_global_status_sort_merge_passes{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Sort Merge Passes"
    },
    {
     "expr": "rate(mysql_global_status_sort_scan{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Sort Scan"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "timeseries",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Slow Queries"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "MySQL Network Traffic",
   "type": "timeseries",
   "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_bytes_received{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Inbound"
    },
    {
     "expr": "rate(mysql_global_status_bytes_sent{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} {{address}} Outbound"
    }
   ]
  },
  { "title": "Commands, Handlers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Top Command Counters",
   "type": "timeseries",
   "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "topk(10, rate(mysql_global_status_commands_total{instance=~\"$instance\"}[5m])>0)",
     "legendFormat": "{{instance}} {{address}} {{command}}"
    }
   ]
  },
  {
   "title": "Select per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=~\"$instance\", command=\"select\"}[1m])",
     "legendFormat": "{{instance}} {{address}} "
    }
   ]
  },
  {
   "title": "Write(insert|update|delete) per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=~\"$instance\", command=~\"insert|update|delete\"}[1m])",
     "legendFormat": "{{instance}} {{address}} {{command}}"
    }
   ]
  },
  {
   "title": "TPS(commit|rollback)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=~\"$instance\", command=~\"commit|rollback\"}[1d])",
     "legendFormat": "{{instance}} {{address}} {{command}}"
    }
   ]
  },
  {
   "title": "MySQL Handlers",
   "type": "timeseries",
   "description": "**MySQL Handlers**\n\nHandler statistics are internal statistics on how MySQL is selecting, updating, inserting, and modifying rows, tables, and indexes.\n\nThis is in fact the layer between the Storage Engine and MySQL.\n\n* `read_rnd_next` is incremented when the server performs a full table scan and this is a counter you don't really want to see with a high value.\n* `read_key` is incremented when a read is done with an index.\n* `read_next` is incremented when the storage engine is asked to 'read the next index entry'. A high value means a lot of index scans are being done.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_handlers_total{instance=~\"$instance\", handler!~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{instance}} {{address}} {{handler}}"
    }
   ]
  },
  {
   "title": "MySQL Transaction Handlers",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_handlers_total{instance=~\"$instance\", handler=~\"commit|rollback|savepoint.*|prepare\"}[5m])",
     "legendFormat": "{{instance}} {{address}} {{handler}}"
    }
   ]
  },
  { "title": "Open Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "MySQL Open Files",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "mysql_global_variables_open_files_limit{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{address}} Open Files Limit"
    },
    {
     "expr": "mysql_global_status_open_files{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{address}} Open Files"
    }
   ]
  },
  { "title": "Table Openings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Table Open Cache Hit Ratio  Mysql 5.6.6+",
   "type": "timeseries",
   "description": "**MySQL Table Open Cache Status**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_table_open_cache_hits{instance=~\"$instance\"}[5m])\n/\n(\nrate(mysql_global_status_table_open_cache_hits{instance=~\"$instance\"}[5m])\n+\nrate(mysql_global_status_table_open_cache_misses{instance=~\"$instance\"}[5m])\n)",
     "legendFormat": "{{instance}} {{address}} Table Open Cache Hit Ratio"
    }
   ]
  },
  {
   "title": "MySQL Open Tables",
   "type": "timeseries",
   "description": "**MySQL Open Tables**\n\nThe recommendation is to set the `table_open_cache_instances` to a loose correlation to virtual CPUs, keeping in mind that more instances means the cache is split more times. If you have a cache set to 500 but it has 10 instances, each cache will only have 50 cached.\n\nThe `table_definition_cache` and `table_open_cache` can be left as default as they are auto-sized MySQL 5.6 and above (ie: do not set them to any value).",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "mysql_global_status_open_tables{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{address}} Open Tables"
    },
    {
     "expr": "mysql_global_variables_table_open_cache{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{address}} Table Open Cache"
    }
   ]
  },
  { "title": "InnoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Read requests / second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}} {{address}}"
    }
   ]
  },
  {
   "title": "Reads from disk / second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 47 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_buffer_pool_reads{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}} {{address}}"
    }
   ]
  },
  {
   "title": "Reads from memory percent",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "100 - increase(mysql_global_status_innodb_buffer_pool_reads{instance=~\"$instance\"}[5m])/increase(mysql_global_status_innodb_buffer_pool_read_requests{instance=~\"$instance\"}[5m]) * 100",
     "legendFormat": "{{instance}} {{address}}"
    }
   ]
  },
  {
   "title": "Row lock waits / second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_row_lock_waits{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}} {{address}}"
    }
   ]
  },
  {
   "title": "Row lock time / second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 51 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_row_lock_time{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}} {{address}}"
    }
   ]
  },
  {
   "title": "Log fsyncs / second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_innodb_os_log_fsyncs{instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}} {{address}}"
    }
   ]
  }
 ]
}