{
 "title": "IPMI",
 "tags": [
  "categraf",
  "grafana",
  "Categraf",
  "latest"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(ipmi_bmc_info,  target)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Power Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_chassis_power_state{target=\"$instance\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Machine Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "ipmi_bmc_info{target=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Fan Speed State",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "ipmi_fan_speed_state{target=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Fan speed in rotations per minute",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_fan_speed_rpm{target=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power Consumption watts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ipmi_dcmi_power_consumption_watts{target=\"$instance\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "ipmi_power_state{target=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Power reading in Watts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_power_watts{target=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IPMI Sensors State",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "ipmi_sensor_state{target=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Temperature State",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "ipmi_temperature_state{target=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_temperature_celsius{target=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reported state of a voltage sensor",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "ipmi_voltage_state{target=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Voltage reading in Volts",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ipmi_voltage_volts{target=\"$instance\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}