{
 "title": "RabbitMQ 3.8+",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "rabbitmq_cluster", "label": "rabbitmq_cluster", "query": { "query": "label_values(rabbitmq_cluster)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ready messages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  {
   "title": "Incoming messages / s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_published_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  {
   "title": "Publishers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channels * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) - sum(rabbitmq_channel_consumers * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_connections * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queues * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  {
   "title": "Unacknowledged messages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  {
   "title": "Outgoing messages / s",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_redelivered_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) +\nsum(rate(rabbitmq_channel_messages_delivered_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) +\nsum(rate(rabbitmq_channel_messages_delivered_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) +\nsum(rate(rabbitmq_channel_get_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) +\nsum(rate(rabbitmq_channel_get_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channel_consumers * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_channels * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rabbitmq_build_info * on(instance) group_left(rabbitmq_cluster) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "nodes",
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rabbitmq_build_info * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}"
    }
   ]
  },
  {
   "title": "Memory available before publishers blocked",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(rabbitmq_resident_memory_limit_bytes * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) -\n(rabbitmq_process_resident_memory_bytes * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  {
   "title": "Disk space available before publishers blocked",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rabbitmq_disk_space_available_bytes * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}"
    }
   ]
  },
  {
   "title": "File descriptors available",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "(rabbitmq_process_max_fds * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) -\n(rabbitmq_process_open_fds * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  {
   "title": "TCP sockets available",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "expr": "(rabbitmq_process_max_tcp_sockets * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) -\n(rabbitmq_process_open_tcp_sockets * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})"
    }
   ]
  },
  { "title": "QUEUED MESSAGES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Messages ready to be delivered to consumers",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Messages pending consumer acknowledgement",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_unacked * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  { "title": "INCOMING MESSAGES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 160 } },
  {
   "title": "Messages published / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_published_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Messages confirmed to publishers / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_confirmed_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Messages routed to queues / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_queue_messages_published_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Messages unconfirmed to publishers / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_unconfirmed[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Unroutable messages dropped / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_unroutable_dropped_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Unroutable messages returned to publishers / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_unroutable_returned_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  { "title": "OUTGOING MESSAGES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 216 } },
  {
   "title": "Messages delivered / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(\n  (rate(rabbitmq_channel_messages_delivered_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) +\n  (rate(rabbitmq_channel_messages_delivered_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"})\n) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Messages redelivered / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_redelivered_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Messages delivered with manual ack / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_delivered_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Messages delivered auto ack / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_delivered_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Messages acknowledged / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_messages_acked_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Polling operations with auto ack / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_get_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Polling operations that yield no result / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_get_empty_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Polling operations with manual ack / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channel_get_ack_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  { "title": "QUEUES", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 288 } },
  {
   "title": "Total queues",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rabbitmq_queues * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}"
    }
   ]
  },
  {
   "title": "Queues declared / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_queues_declared_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Queues created / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_queues_created_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Queues deleted / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_queues_deleted_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  { "title": "CHANNELS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 328 } },
  {
   "title": "Total channels",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rabbitmq_channels * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}"
    }
   ]
  },
  {
   "title": "Channels opened / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channels_opened_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Channels closed / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_channels_closed_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  { "title": "CONNECTIONS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 360 } },
  {
   "title": "Connections closed / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_connections_closed_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  },
  {
   "title": "Total connections",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rabbitmq_connections * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}"
    }
   ]
  },
  {
   "title": "Connections opened / s",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rabbitmq_connections_opened_total[60s]) * on(instance) group_left(rabbitmq_cluster, rabbitmq_node) rabbitmq_identity_info{rabbitmq_cluster=\"$rabbitmq_cluster\"}) by(rabbitmq_node)"
    }
   ]
  }
 ]
}