{
 "title": "Kubernetes / Proxy (dashboard-by-ident)",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "ident",
    "label": "ident",
    "query": {
     "query": "label_values(kubeproxy_sync_proxy_rules_iptables_restore_failures_total, ident)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"kube-proxy\"})"
    }
   ]
  },
  {
   "title": "Rules Sync Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kubeproxy_sync_proxy_rules_duration_seconds_count{job=\"kube-proxy\", ident=~\"$ident\"}[5m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Rule Sync Latency 99th Quantile",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,rate(kubeproxy_sync_proxy_rules_duration_seconds_bucket{job=\"kube-proxy\", ident=~\"$ident\"}[5m]))",
     "legendFormat": "{{ident}}"
    }
   ]
  },
  {
   "title": "Network Programming Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(kubeproxy_network_programming_duration_seconds_count{job=\"kube-proxy\", ident=~\"$ident\"}[5m]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Network Programming Latency 99th Quantile",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kubeproxy_network_programming_duration_seconds_bucket{job=\"kube-proxy\", ident=~\"$ident\"}[5m])) by (ident, le))",
     "legendFormat": "{{ident}}"
    }
   ]
  },
  {
   "title": "Kube API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-proxy\", ident=~\"$ident\",code=~\"2..\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-proxy\", ident=~\"$ident\",code=~\"3..\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-proxy\", ident=~\"$ident\",code=~\"4..\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(rest_client_requests_total{job=\"kube-proxy\", ident=~\"$ident\",code=~\"5..\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Post Request Latency 99th Quantile",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"kube-proxy\",ident=~\"$ident\",verb=\"POST\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Get Request Latency 99th Quantile",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_duration_seconds_bucket{job=\"kube-proxy\", ident=~\"$ident\", verb=\"GET\"}[5m])) by (verb, url, le))",
     "legendFormat": "{{verb}} {{url}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"kube-proxy\",ident=~\"$ident\"}",
     "legendFormat": "{{ident}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kube-proxy\",ident=~\"$ident\"}[5m])",
     "legendFormat": "{{ident}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"kube-proxy\",ident=~\"$ident\"}",
     "legendFormat": "{{ident}}"
    }
   ]
  }
 ]
}