{
 "title": "BIND 9",
 "tags": [ "bind 9" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Memory Total Use",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 4 },
   "targets": [
    { "expr": "bind_memory_total_use", "legendFormat": "{{url}}" }
   ]
  },
  {
   "title": "Query Counters",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 4, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "sum by (__name__, url) ({__name__=~\"bind_counter_.*\", type=\"qtype\"})",
     "legendFormat": "{{__name__}} {{url}}"
    }
   ]
  },
  {
   "title": "Request Counters",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 4, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "sum by (__name__, url) ({__name__=~\"bind_counter_.*\", type=\"opcode\"})",
     "legendFormat": "{{__name__}} {{url}}"
    }
   ]
  },
  {
   "title": "Response Code Counters",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "sum by (__name__, url) ({__name__=~\"bind_counter_.*\", type=\"rcode\"})",
     "legendFormat": "{{__name__}} {{url}}"
    }
   ]
  },
  {
   "title": "Total Use Memory (Context)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    { "expr": "bind_memory_context_total", "legendFormat": "Total Use" }
   ]
  },
  {
   "title": "In Use Memory (Context)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 8 },
   "targets": [
    { "expr": "bind_memory_context_in_use", "legendFormat": "In Use" }
   ]
  }
 ]
}