{
 "title": "AWS CloudWatch",
 "tags": [ "aws cloudwatch" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "AWS ELB Latency Average",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cloudwatch_aws_elb_latency_average",
     "legendFormat": "{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "AWS ELB Request Count",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cloudwatch_aws_elb_request_count_sum",
     "legendFormat": "{{load_balancer_name}}"
    }
   ]
  },
  {
   "title": "AWS EC2 CPU Utilization Average",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cloudwatch_aws_ec2_cpu_utilization_average",
     "legendFormat": "{{instance_id}}"
    }
   ]
  },
  {
   "title": "AWS RDS CPU Utilization Average",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cloudwatch_aws_rds_cpu_utilization_average",
     "legendFormat": "{{db_instance_identifier}}"
    }
   ]
  }
 ]
}