{
 "title": "Jenkins CI/CD Metrics",
 "tags": [ "jenkins ci/cd metrics" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Jenkins Up Status",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "jenkins_up", "legendFormat": "Node: {{node_name}}" }
   ]
  },
  {
   "title": "Jenkins Job Result Code",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "jenkins_job_result_code", "legendFormat": "Job: {{name}}" }
   ]
  },
  {
   "title": "Jenkins Job Duration (ms)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "jenkins_job_duration", "legendFormat": "Job: {{name}}" }
   ]
  },
  {
   "title": "Jenkins Busy Executors",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "jenkins_busy_executors", "legendFormat": "Busy" }
   ]
  },
  {
   "title": "Jenkins Node Disk Available (Bytes)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    { "expr": "jenkins_node_disk_available", "legendFormat": "Node: {{node_name}}" }
   ]
  },
  {
   "title": "Jenkins Node Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    { "expr": "jenkins_node_response_time", "legendFormat": "Node: {{node_name}}" }
   ]
  }
 ]
}