{
 "title": "Vsphere (dashboards)",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "vcenter", "label": "vcenter", "query": { "query": "vsphere_host_cpu_usage_average" } },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "vsphere_host_cpu_usage_average{vcenter=\"$vcenter\"}"
    }
   },
   {
    "name": "esxi",
    "label": "esxi",
    "query": {
     "query": "vsphere_host_cpu_usage_average{vcenter=\"$vcenter\"}"
    }
   },
   {
    "name": "vmname",
    "label": "vmname",
    "query": {
     "query": "vsphere_vm_sys_uptime_latest{vcenter=\"$vcenter\"}"
    }
   },
   {
    "name": "datastore",
    "label": "datastore",
    "query": {
     "query": "vsphere_datastore_disk_provisioned_latest{vcenter=\"$vcenter\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "vSphere Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel 2",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(vsphere_host_cpu_usage_average) by(vcenter))",
     "legendFormat": "vCenter Summary"
    },
    {
     "expr": "count(count(vsphere_host_cpu_usage_average) by(clustername))",
     "legendFormat": "Cluster Summary"
    },
    {
     "expr": "count(count(vsphere_host_cpu_usage_average) by(esxhostname))",
     "legendFormat": "ESXi Summary"
    },
    {
     "expr": "count(count(vsphere_vm_cpu_used_summation) by(vmname))",
     "legendFormat": "VM Summary"
    },
    {
     "expr": "count(count(vsphere_datastore_disk_used_latest) by(dsname))",
     "legendFormat": "Datastore Summary"
    }
   ]
  },
  {
   "title": "EXSI cpu使用率排名",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(vsphere_host_cpu_usage_average{}) by(esxhostname)/count(vsphere_host_cpu_usage_average{}) by(esxhostname))",
     "legendFormat": "{{esxhostname}}"
    }
   ]
  },
  {
   "title": "EXSI mem使用率排名",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(vsphere_host_mem_usage_average{}) by(esxhostname)/count(vsphere_host_mem_usage_average{}) by(esxhostname))",
     "legendFormat": "{{esxhostname}}"
    }
   ]
  },
  {
   "title": "VM cpu使用率排名",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(vsphere_vm_cpu_usage_average{}) by(vmname)/count(vsphere_vm_cpu_usage_average{}) by(vmname))",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "VM mem使用率排名",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(vsphere_vm_mem_usage_average{}) by(vmname)/count(vsphere_vm_mem_usage_average{}) by(vmname))",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(vsphere_host_sys_uptime_latest{clustername=\"$Cluster\",vcenter=\"$vcenter\"}) by(clustername)/count(vsphere_host_sys_uptime_latest{clustername=\"$Cluster\",vcenter=\"$vcenter\"}) by(clustername))/86500"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 14 },
   "targets": [
    {
     "expr": "(sum(vsphere_host_cpu_usage_average{clustername=\"$Cluster\",vcenter=\"$vcenter\"}) by(clustername)/count(vsphere_host_cpu_usage_average{clustername=\"$Cluster\",vcenter=\"$vcenter\"}) by(clustername))",
     "legendFormat": "{{clustername}}"
    }
   ]
  },
  {
   "title": "Cluster RAM Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 14 },
   "targets": [
    {
     "expr": "(sum(vsphere_host_mem_usage_average{clustername=\"$Cluster\",vcenter=\"$vcenter\"}) by(clustername)/count(vsphere_host_mem_usage_average{clustername=\"$Cluster\",vcenter=\"$vcenter\"}) by(clustername))",
     "legendFormat": "{{clustername}}"
    }
   ]
  },
  {
   "title": "Cluster Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(vsphere_host_net_bytesRx_average{clustername=\"$Cluster\",vcenter=\"$vcenter\"}) by(clustername))/1000 ",
     "legendFormat": "{{clustername}}-net_bytesRx"
    },
    {
     "expr": "(sum(vsphere_host_net_bytesTx_average{clustername=\"$Cluster\",vcenter=\"$vcenter\"}) by(clustername))/1000",
     "legendFormat": "{{clustername}}-net_bytesTx"
    }
   ]
  },
  {
   "title": "Panel 12",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 14 },
   "targets": [
    {
     "expr": "sum(vsphere_datastore_disk_capacity_latest{vcenter=\"$vcenter\"}) by(source)",
     "legendFormat": "总量"
    },
    {
     "expr": "sum(vsphere_datastore_disk_used_latest{vcenter=\"$vcenter\"}) by(source)",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(vsphere_datastore_disk_used_latest{vcenter=\"$vcenter\"}/vsphere_datastore_disk_capacity_latest{vcenter=\"$vcenter\"}) by(source)*100",
     "legendFormat": "使用率(%)"
    }
   ]
  },
  { "title": "Exsi status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "uptime\n",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_host_sys_uptime_latest{esxhostname=\"$esxi\"}",
     "legendFormat": "{{esxhostname}}"
    }
   ]
  },
  {
   "title": "Host CPU Ready Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(vsphere_host_cpu_ready_summation{vcenter=\"$vcenter\",esxhostname=\"$esxi\"}) by(esxhostname)/count(vsphere_host_cpu_ready_summation{vcenter=\"$vcenter\",esxhostname=\"$esxi\"}) by(esxhostname))",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "Host CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 20 },
   "targets": [
    {
     "expr": "(sum(vsphere_host_cpu_usage_average{vcenter=\"$vcenter\",esxhostname=\"$esxi\"}) by(esxhostname)/count(vsphere_host_cpu_usage_average{vcenter=\"$vcenter\",esxhostname=\"$esxi\"}) by(esxhostname))",
     "legendFormat": "{{esxhostname}}"
    }
   ]
  },
  {
   "title": "Host RAM Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 20 },
   "targets": [
    {
     "expr": "(sum(vsphere_host_mem_usage_average{vcenter=\"$vcenter\",esxhostname=\"$esxi\"}) by(esxhostname)/count(vsphere_host_mem_usage_average{vcenter=\"$vcenter\",esxhostname=\"$esxi\"}) by(esxhostname))",
     "legendFormat": "{{esxhostname}}"
    }
   ]
  },
  {
   "title": "Cluster Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(vsphere_host_net_bytesRx_average{clustername=\"$Cluster\",vcenter=\"$vcenter\"}) by(esxhostname))/1000",
     "legendFormat": "{{esxhostname}}-net_bytesRx"
    },
    {
     "expr": "(sum(vsphere_host_net_bytesTx_average{clustername=\"$Cluster\",vcenter=\"$vcenter\"}) by(esxhostname))/1000",
     "legendFormat": "{{esxhostname}}-net_bytesTx"
    }
   ]
  },
  { "title": "VMs status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vsphere_vm_sys_uptime_latest{vmname=\"$vmname\"}",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "VM CPU Ready Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 2, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(vsphere_vm_cpu_ready_summation{vcenter=\"$vcenter\",vmname=\"$vmname\"}) by(vmname)/count(vsphere_vm_cpu_ready_summation{vcenter=\"$vcenter\",vmname=\"$vmname\"}) by(vmname))",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "VM CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(vsphere_vm_cpu_usage_average{vcenter=\"$vcenter\",vmname=\"$vmname\"}) by(vmname)/count(vsphere_vm_cpu_usage_average{vcenter=\"$vcenter\",vmname=\"$vmname\"}) by(vmname))",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "VM RAM Usage in %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 26 },
   "targets": [
    {
     "expr": "(sum(vsphere_vm_mem_usage_average{vcenter=\"$vcenter\",vmname=\"$vmname\"}) by(vmname)/count(vsphere_vm_mem_usage_average{vcenter=\"$vcenter\",vmname=\"$vmname\"}) by(vmname))",
     "legendFormat": "{{vmname}}"
    }
   ]
  },
  {
   "title": "VMNetwork Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(vsphere_vm_net_bytesRx_average{vmname=\"$vmname\",vcenter=\"$vcenter\"}) by(vmname))/1000",
     "legendFormat": "{{vmname}}-net_bytesRx"
    },
    {
     "expr": "(sum(vsphere_vm_net_bytesTx_average{vmname=\"$vmname\",vcenter=\"$vcenter\"}) by(vmname))/1000",
     "legendFormat": "{{vmname}}-net_bytesTx"
    }
   ]
  }
 ]
}