{
 "title": "Oracle - 模板",
 "tags": [
  "categraf",
  "grafana",
  "Telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "ident", "label": "ident", "query": { "query": "label_values(ident)" } },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Activities", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "execute count / second",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(oracle_activity_execute_count_value{ident=\"$ident\", instance=\"$instance\"}[2m])"
    }
   ]
  },
  {
   "title": "user commits / second",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(oracle_activity_user_commits_value{ident=\"$ident\", instance=\"$instance\"}[2m])"
    }
   ]
  },
  {
   "title": "user rollbacks / second",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(oracle_activity_user_rollbacks_value{ident=\"$ident\", instance=\"$instance\"}[2m])"
    }
   ]
  },
  {
   "title": "status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "oracle_up{ident=\"$ident\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Waits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Time waited",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "oracle_wait_time_value{ident=\"$ident\", instance=\"$instance\"}",
     "legendFormat": "{{wait_class}}"
    }
   ]
  },
  { "title": "Tablespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Used Percent",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "oracle_tablespace_bytes{ident=\"$ident\", instance=\"$instance\"}/oracle_tablespace_max_bytes{ident=\"$ident\", instance=\"$instance\"}",
     "legendFormat": "{{tablespace}}"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "oracle_tablespace_free{ident=\"$ident\", instance=\"$instance\"}",
     "legendFormat": "{{tablespace}}"
    }
   ]
  },
  { "title": "IO and TPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 } },
  {
   "title": "IO Requests / Second",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "oracle_sysmetric_io_requests_per_second_value{ident=\"$ident\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "oracle_sysmetric_user_transaction_per_sec_value{ident=\"$ident\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "IO Bytes / Second",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "oracle_sysmetric_io_megabytes_per_second_value{ident=\"$ident\", instance=\"$instance\"}*1024*1024"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "oracle_sessions_value{ident=\"$ident\", instance=\"$instance\",status=\"ACTIVE\"}"
    }
   ]
  },
  { "title": "Hit Ratio", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Buffer Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "oracle_sysmetric_buffer_cache_hit_ratio_value{ident=\"$ident\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Redo Allocation Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "oracle_sysmetric_redo_allocation_hit_ratio_value{ident=\"$ident\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Row Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "oracle_sysmetric_row_cache_hit_ratio_value{ident=\"$ident\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Library Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "oracle_sysmetric_library_cache_hit_ratio_value{ident=\"$ident\", instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Physical Read Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 } },
  {
   "title": "Physical Read Write Bytes / Second",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "oracle_sysmetric_physical_read_bytes_per_sec_value{ident=\"$ident\", instance=\"$instance\"}"
    },
    {
     "expr": "oracle_sysmetric_Physical_Write_Bytes_Per_Sec{ident=\"$ident\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Physical Read Write Total Bytes / Second",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "oracle_sysmetric_physical_read_total_bytes_per_sec_value{ident=\"$ident\", instance=\"$instance\"}"
    },
    {
     "expr": "oracle_sysmetric_Physical_Write_Total_Bytes_Per_Sec{ident=\"$ident\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Physical RW IO Requests / Second",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "oracle_sysmetric_physical_read_io_requests_per_sec_value{ident=\"$ident\", instance=\"$instance\"}"
    },
    {
     "expr": "oracle_sysmetric_Physical_Write_IO_Requests_Per_Sec{ident=\"$ident\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Physical RW Total IO Requests / Second",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "oracle_sysmetric_physical_read_total_io_requests_per_sec_value{ident=\"$ident\", instance=\"$instance\"}"
    },
    {
     "expr": "oracle_sysmetric_Physical_Write_Total_IO_Requests_Per_Sec{ident=\"$ident\", instance=\"$instance\"}"
    }
   ]
  }
 ]
}