{
 "title": "Docker Containers",
 "tags": [ "docker containers" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Docker CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Docker Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "docker_container_mem_usage_percent",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Docker Net RX (Bytes)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(docker_container_net_rx_bytes[5m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Docker Net TX (Bytes)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(docker_container_net_tx_bytes[5m])",
     "legendFormat": "{{container_name}}"
    }
   ]
  }
 ]
}