{
 "title": "网络交换机",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "IP",
    "label": "IP",
    "query": {
     "query": "label_values(switch_legacy_if_in,ip)"
    }
   },
   {
    "name": "Interface",
    "label": "Interface",
    "query": {
     "query": "label_values(switch_legacy_if_in{ip=\"$IP\"},ifname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "总体概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "交换机数目",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(switch_legacy_sysUpTime)" }
   ]
  },
  {
   "title": "CPU使用率排名",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "switch_legacy_cpu_util", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "网络in流量大于300MB",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(switch_legacy_if_in) by(ip)>300000000",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "采集耗时",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "switch_legacy_ifstat_use_time_sec",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "内存使用率排名",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "switch_legacy_mem_util", "legendFormat": "{{ip}}" }
   ]
  },
  {
   "title": "网络out流量大于300MB",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(switch_legacy_if_out) by(ip)>300000000",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "设备运行时长",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "switch_legacy_sysUpTime/100/(24*3600)",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "设备温度",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "switch_legacy_TempStatus", "legendFormat": "{{ip}}" }
   ]
  },
  { "title": "单机详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "cpu使用率",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "switch_legacy_cpu_util{ip=\"$IP\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "网络in流量",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "switch_legacy_if_in{ip=\"$IP\"}>0",
     "legendFormat": "{{ip}}-{{ifname}}"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "switch_legacy_mem_util{ip=\"$IP\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "网络out流量",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "switch_legacy_if_out{ip=\"$IP\"}>0",
     "legendFormat": "{{ip}}-{{ifname}}"
    }
   ]
  }
 ]
}