{
 "title": "postgresql大盘",
 "tags": [
  "categraf",
  "grafana"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(postgresql_datid,server)"
    }
   },
   {
    "name": "db",
    "label": "db",
    "query": {
     "query": "label_values(postgresql_datid{server=\"$server\"},db)"
    }
   }
  ]
 },
 "panels": [
  { "title": "pg_stat_database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "连接数",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgresql_numbackends{server=\"$server\",db=\"$db\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "缓存命中率",
   "type": "stat",
   "description": "命中率低于99%，就需要适当调大shared buffer",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgresql_blks_hit{server=\"$server\",db=\"$db\"}/(postgresql_blks_hit{server=\"$server\",db=\"$db\"}+postgresql_blks_read{server=\"$server\",db=\"$db\"})",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "死锁数",
   "type": "stat",
   "description": "死锁的数量，如果这个值很大说明业务逻辑有问题",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgresql_deadlocks{server=\"$server\",db=\"$db\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "冲突数",
   "type": "stat",
   "description": "与恢复冲突取消的查询次数，只会在备机上发生",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgresql_conflicts{server=\"$server\",db=\"$db\"}",
     "legendFormat": "{{db}}"
    }
   ]
  },
  {
   "title": "事务统计",
   "type": "timeseries",
   "description": "rollback 过多，则需要检查业务逻辑，表面业务逻辑存在问题",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "increase(postgresql_xact_commit{server=\"$server\",db=\"$db\"}[5m])",
     "legendFormat": "commit"
    },
    {
     "expr": "increase(postgresql_xact_rollback{server=\"$server\",db=\"$db\"}[5m])",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "数据查询统计",
   "type": "timeseries",
   "description": "returned ,代表执行查询遍历行数\nfetched，代表返回给客户端的行数\nreturned 远大于 fetched，代表查询效率低，存在全表扫描，应增加索引进行优化",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "increase(postgresql_tup_returned{server=\"$server\",db=\"$db\"}[5m])",
     "legendFormat": "returned"
    },
    {
     "expr": "increase(postgresql_tup_fetched{server=\"$server\",db=\"$db\"}[5m])",
     "legendFormat": "fetched"
    }
   ]
  },
  {
   "title": "数据更新统计",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(postgresql_tup_inserted{server=\"$server\",db=\"$db\"}[5m])",
     "legendFormat": "inserted"
    },
    {
     "expr": "increase(postgresql_tup_updated{server=\"$server\",db=\"$db\"}[5m])",
     "legendFormat": "updated"
    },
    {
     "expr": "increase(postgresql_tup_deleted{server=\"$server\",db=\"$db\"}[5m])",
     "legendFormat": "deleted"
    }
   ]
  },
  {
   "title": "生成临时文件统计",
   "type": "timeseries",
   "description": "temp_files较高说明存在很多排序，hash,或者聚合这种操作，可以增大work_mem减少临时文件的产生，并且同时这些操作的性能也会有较大的提升",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(postgresql_temp_files{server=\"$server\",db=\"$db\"}[5m])",
     "legendFormat": "temp_files"
    },
    {
     "expr": "increase(postgresql_temp_bytes{server=\"$server\",db=\"$db\"}[5m])",
     "legendFormat": "temp_bytes"
    }
   ]
  },
  {
   "title": "数据库读写时间统计",
   "type": "timeseries",
   "description": "数据库中花费在读取文件的时间，这个值很高说明内存较小，需要频繁从磁盘读入数据文件\n数据库中花费在写数据文件的时间，pg中脏页一般写入page cache，如果这个值较高，则说明cache较小，操作系统的cache需要更积极的写入",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(postgresql_blk_read_time{server=\"$server\",db=\"$db\"}[5m])",
     "legendFormat": "blk_read_time"
    },
    {
     "expr": "increase(postgresql_blk_write_time{server=\"$server\",db=\"$db\"}[5m])",
     "legendFormat": "blk_write_time"
    }
   ]
  },
  { "title": "pg_stat_bgwriter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "checkpoint分布",
   "type": "timeseries",
   "description": "postgresql_checkpoints_timed：指超过checkpoint_timeout的时间后触发的检查点次数\npostgresql_checkpoints_req：手动触发checkpoint或者因为WAL文件数量达到max_wal_size时也会增加，如果这个值大于postgresql_checkpoints_timed说明checkpoint_timeout设置的不合理",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(postgresql_checkpoints_timed{server=\"$server\"}[5m])",
     "legendFormat": "postgresql_checkpoints_timed"
    },
    {
     "expr": "increase(postgresql_checkpoints_req{server=\"$server\"}[5m])",
     "legendFormat": "postgresql_checkpoints_req"
    }
   ]
  },
  {
   "title": "checkpoint 写文件时间分布",
   "type": "timeseries",
   "description": "checkpoint_write_time: 从shared buffer 中write到page cache花费的时间\ncheckpoint_sync_time  : checkpoint调用fsync将脏数据刷到磁盘花费的时间，如果这个值很长，容易造成IO抖动，需要增加checkpoint_timeout或者checkpoint_completion_target",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "increase(postgresql_checkpoint_write_time{server=\"$server\"}[5m])",
     "legendFormat": "checkpoint_write_time"
    },
    {
     "expr": "increase(postgresql_checkpoint_sync_time{server=\"$server\"}[5m])",
     "legendFormat": "checkpoint_sync_time"
    }
   ]
  },
  {
   "title": "数据块写入分布",
   "type": "timeseries",
   "description": "buffers_checkpoint: checkpoint写数据块数量\nbuffers_clean：bgwriter写入数据块的数量\nbuffers_backend:通过backend写入的块数量, 此值过大，代表shared buffer没有维护好，后端进程不得不自己去进行刷盘的动作\nbuffers_backend_fsync: backend需要fsync的次数\n",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(postgresql_buffers_checkpoint{server=\"$server\"}[5m])",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "increase(postgresql_buffers_clean{server=\"$server\"}[5m])",
     "legendFormat": "buffers_clean"
    },
    {
     "expr": "increase(postgresql_buffers_backend{server=\"$server\"}[5m])",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "increase(postgresql_buffers_backend_fsync{server=\"$server\"}[5m])",
     "legendFormat": "buffers_backend_fsync"
    }
   ]
  }
 ]
}