{
 "title": "Redis Sentinel Status",
 "tags": [ "redis sentinel status" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Sentinel Uptime (days)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "redis_sentinel_uptime_in_seconds / 86400",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Sentinel Connected Clients",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "redis_sentinel_connected_clients",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Master Monitored Sentinels",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "redis_sentinel_master_sentinels",
     "legendFormat": "Master: {{master}}"
    }
   ]
  },
  {
   "title": "Master Attached Slaves",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "redis_sentinel_master_slaves", "legendFormat": "Master: {{master}}" }
   ]
  }
 ]
}