{
 "title": "Linux IPVS Metrics",
 "tags": [ "linux ipvs metrics" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "IPVS Real Server Active Connections",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "ipvs_active_connections", "legendFormat": "RS: {{address}}:{{port}}" }
   ]
  },
  {
   "title": "IPVS Real Server Inactive Connections",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "ipvs_inactive_connections", "legendFormat": "RS: {{address}}:{{port}}" }
   ]
  },
  {
   "title": "IPVS Connections",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "ipvs_connections", "legendFormat": "{{address}}:{{port}}" }
   ]
  },
  {
   "title": "IPVS CPS",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "ipvs_cps", "legendFormat": "{{address}}:{{port}}" }
   ]
  }
 ]
}