{
 "title": "NFS Client Metrics",
 "tags": [ "nfs client metrics" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "NFS Client Read/Write Bytes/s",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(nfsclient_bytes_read[5m])", "legendFormat": "Read: {{mountpoint}}" },
    {
     "expr": "rate(nfsclient_bytes_write[5m])",
     "legendFormat": "Write: {{mountpoint}}"
    }
   ]
  },
  {
   "title": "NFS Client Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(nfsclient_ops_response_time_ms[5m]) / rate(nfsclient_ops_ops[5m])",
     "legendFormat": "{{mountpoint}} ({{operation}})"
    }
   ]
  },
  {
   "title": "NFS Client Operations/s",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(nfsclient_ops_ops[5m])", "legendFormat": "{{mountpoint}} ({{operation}})" }
   ]
  },
  {
   "title": "NFS Client Timeouts/s",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(nfsclient_ops_timeouts[5m])",
     "legendFormat": "{{mountpoint}} ({{operation}})"
    }
   ]
  }
 ]
}