# # collect interval
#interval = 3600
#

#[mappings]
#"baidu.com" = { "app" = "baidu" }
#"google.com" = { "app" = "google" }

#[[instances]]
## [deprecated] Used to collect domain name information.
#domain = "baidu.com"

# domains 
#domains = ["baidu.com","google.com","aliyun.com"]

## timeout in seconds
# timeout = 30

## whois server
# server = "whois.iana.org"

## append some labels for series
#labels = { region="n9e", product="test1" }

## interval = global.interval * interval_times
#interval_times = 1

## concurrent
# concurrent = 1


#[[instances]]
## Used to collect domain name information.
#domain = "google.com"

## append some labels for series
#labels = { region="n9e", product="test2" }

## interval = global.interval * interval_times
#interval_times = 1

