{
 "title": "CPU Metrics",
 "tags": [ "cpu metrics" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU Active Usage (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cpu_usage_active{cpu=\"cpu-total\"}",
     "legendFormat": "Total Active"
    }
   ]
  },
  {
   "title": "CPU IOWait (%)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cpu_usage_iowait{cpu=\"cpu-total\"}",
     "legendFormat": "Total IOWait"
    }
   ]
  },
  {
   "title": "CPU System Time (%)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\"}",
     "legendFormat": "Total System"
    }
   ]
  },
  {
   "title": "CPU User Time (%)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\"}",
     "legendFormat": "Total User"
    }
   ]
  }
 ]
}