# # collect interval
# interval = 15

## If true, chronyc tries to perform a DNS lookup for the time server.
#dns_lookup = false

# Get standard chrony metrics, requires chronyc executable.
#chronyc_command = "/usr/bin/chronyc"
chronyc_command = ""