{
 "title": "Linux Kernel Metrics",
 "tags": [ "linux kernel metrics" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Kernel Context Switches/s",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(kernel_context_switches[5m])",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Kernel Interrupts/s",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(kernel_interrupts[5m])", "legendFormat": "{{agent_hostname}}" }
   ]
  },
  {
   "title": "Kernel Processes Forked/s",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(kernel_processes_forked[5m])",
     "legendFormat": "{{agent_hostname}}"
    }
   ]
  },
  {
   "title": "Kernel Entropy Available",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    { "expr": "kernel_entropy_avail", "legendFormat": "{{agent_hostname}}" }
   ]
  }
 ]
}