daysUntilStale: 60
daysUntilClose: 7
exemptLabels:
  - pinned
  - security
  - bug
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.
closeComment: >
  This issue has been automatically closed due to inactivity. Please reopen if needed.
